### ISSUE TITLE
Extra Space in the code

### ISSUE THREAD

**Issue by dab2020** [BobHasNoSoul/jellyfin-mods#1]
In the first part of Jellyfin-mods, for the force backdrops you seem to accidently have added a space
Like: 
    `enableBackdrops:function() {return _}`
where it should be
    `enableBackdrops:function(){return _}`
same for what to replace with
It is 
    `enableBackdrops:function() {return x}`
while is should be
    `enableBackdrops:function(){return x}`

**Comment by BobHasNoSoul** [comment]
thanks for bringing this to my attention, you are absolutely right im not quite sure how i put an extra space in there (even my main bundle js on my server hasn't got one..) i have rectified this as reflected in the readme.. thank you again.
