### ISSUE TITLE
Force backdrops for all users for new stable 10.8 !

### ISSUE THREAD

**Issue by VigibotDev** [BobHasNoSoul/jellyfin-mods#10]
Hello,

On the new 10.8.0 stable, I get this on the original package file:

,enableBackdrops:function(){return x}

I replaced with

,enableBackdrops:function(){return _}

And it work !
Trick is just inverted, can you explain this ? :D

**Comment by Xiphan** [comment]
Thanks for the fix. Any idea what the new return is for `enableThemeSongs:function(){return k}`?

**Comment by LeviSnoot** [comment]
Should be fixed with #11.

**Comment by LeviSnoot** [comment]
> Thanks for the fix. Any idea what the new return is for `enableThemeSongs:function(){return k}`?

@Xiphan I believe I've fixed this, can you test and let me know if it worked?

**Comment by Xiphan** [comment]
> @Xiphan I believe I've fixed this, can you test and let me know if it worked?

Yes, it's working now! Thank you.

**Comment by brkr1** [comment]
> And changing it to an underscore no longer works, at least not for theme tunes. It works for backdrops, but it does something weird for theme tunes in that it ticks the box when I check my profile under an incognito tab. But theme tunes don't actually play.

It's happening the same to me. Have you figured out how to make it play?

**Comment by VigibotDev** [comment]
Now it's :

enableBackdrops:function(){return R}
to
enableBackdrops:function(){return M}

**Comment by brkr1** [comment]
> Now it's :
> 
> enableBackdrops:function(){return R} to enableBackdrops:function(){return M}

Backdrops are working. Themesongs that are broken.
