### ISSUE TITLE
Logos issues

### ISSUE THREAD

**Issue by DevilsDesigns** [BobHasNoSoul/jellyfin-mods#22]
bob am i doing something wrong

```

<img src="C:/Program Files/Jellyfin/Server/jellyfin-web/logo.png" width=350px style="padding: 0px;display:block; margin-left: auto; margin-right: auto;">

```

i added this to my file and i get a blank image

![image](https://github.com/BobHasNoSoul/jellyfin-mods/assets/35183970/bda9f40f-aed7-49be-975f-f1816985fd49)

img link c://Program Files/Jellyfin/Server/jellyfin-web/logo.jpg so i is correct. any ideas why this would be happening

**Comment by BobHasNoSoul** [comment]
Okay so yes, it has to be visible from webroot not a drive link so your clients can see it the correct link for that file should be "/web/logo.jpg" 
Because that /web/ means webroot on your jellyfin setup.
