### ISSUE TITLE
Logo next to hamburger menu

### ISSUE THREAD

**Issue by DevilsDesigns** [BobHasNoSoul/jellyfin-mods#24]
![image](https://github.com/BobHasNoSoul/jellyfin-mods/assets/35183970/11c52292-cad1-4cb5-a251-238636751c5a)
this logo wont change. is there a way to remove it or change it?

**Comment by BobHasNoSoul** [comment]
in 10.9.x it changed where icons are and some icon names so two choices

replace the file /web/assets/img/banner-light.png with your own one  (or banner-dark.png if you use the "dark" theme)

or use the css to have it changed that being (obviously change the weblink

`.pageTitleWithDefaultLogo {    background-image: url(https://example.com/myawesomenewserverlogo.png) !important;}`

final step clear cache and reload.. if you are unsure how to do this most browsers will do this for a single page using ctrl+shift+r
