### ISSUE TITLE
Add custom link to side bar 10.9.x (How to add icon)

### ISSUE THREAD

**Issue by Jchasa** [BobHasNoSoul/jellyfin-mods#28]
Not sure how to add an actual icon, or what .css file would need to be edited.  Could we get more detailed instructions.  Thanks.

**Comment by Jchasa** [comment]
So I figured out how to add from the Material Designs, although I was hoping for a way to add a custom icon, Thanks.

Partial solution is to click on the Material Design link provided and use the name of the icon in the code snippet provided.

**Comment by BobHasNoSoul** [comment]
To add a custom icon you would need to modify the actual side menu.. this
can be problematic and not as straightforward as doing the links as
mentioned. I can look into this when I'm free from work (looks like
Wednesday)

**Comment by aaemon** [comment]
I do not know why I can not find the config.json file in /usr/share/jellyfin/web directory. I searched for config.json file in other directories as well. 
I am using Jellyfin 10.9.8 and installed on Ubuntu 22.04.
