### ISSUE TITLE
Where is snowflakes.css

### ISSUE THREAD

**Issue by Poiaman** [BobHasNoSoul/jellyfin-mods#29]
I cant find this file even in old version, only snow.css and snowstorm.js

**Comment by BobHasNoSoul** [comment]
That may have been a typo on my end, it is snow.css my mistake

**Comment by Poiaman** [comment]
Thanks for the feedback, I had already thought that this could be the case and I had already tried to change the direction to snow.css and it didn't work, I thought it could be a conflict with my CSS and I also disabled them all for testing, but it still doesn't work. Snowstorm.JS works perfectly, but I'm pretty noob with coding so it could be some silly detail that I'm not identifying.

**Comment by BobHasNoSoul** [comment]
When I get off from work I can talk you through it via discord then I can
simplify the instructions accordingly

If you have discord that is

**Comment by BobHasNoSoul** [comment]
UPDATE: i have checked and updated the files and made it copy the same as my setup so it should* work.. if the error persists let me know and i will find a way to help with it.

**Comment by Poiaman** [comment]
It worked perfectly, thanks for the support!

**Comment by BobHasNoSoul** [comment]
No worries glad I could help :)
