### ISSUE TITLE
Intro plugin, intro skipper, and "official" status

### ISSUE THREAD

**Issue by AbandonedCart** [BobHasNoSoul/jellyfin-mods#42]
The intro plugin allowed you to inject a video that plays before your content. This is not be confused with intro skipper, which allows skipping past the opening theme (or intro) of shows. The original repository has been discontinued and https://github.com/jumoog/intro-skipper is widely accepted as the successor. In addition to general improvements and compatibility with 10.9, it has also finished some of the features proposed in the original project (ie skipping credits).

I would submit a PR, but I don't want to make any assumptions about what you'd consider relevant or if you actually meant to advertise the pre-roll plugin?

**Comment by LeviSnoot** [comment]
It looks like this has been fixed, at least from checking the readme in its current state.

**Comment by AbandonedCart** [comment]
> It looks like this has been fixed, at least from checking the readme in its current state.

Thanks for notifying me. Unfortunately, I haven't really had time to keep checking up on it manually.
