### ISSUE TITLE
Requests Tab Too High

### ISSUE THREAD

**Issue by kylehandy123** [BobHasNoSoul/jellyfin-mods#48]
I did the requests tab mod. Upon doing so, it works, but the requests tab is too high up on the page, meaning the Jellyseerr search bar is behind the top bar of Jellyfin.

See image.

![Screenshot_1305](https://github.com/user-attachments/assets/ba8d1d18-3e10-4822-8fcc-3dcfb1ff8033)

Anyone know how to correct this?

**Comment by apensotti** [comment]
Replace:

```
<style>:root{--save-gut:max(env(safe-area-inset-left),3.3%)}.requestIframe{margin:0 .4em;padding:0 var(--save-gut);width:calc(100% - (.4em * 2) - (var(--save-gut) * 2));height:85vh;border:none;position:absolute;top:0}</style><script>setTimeout(() => {createRequestTab()}, 500)</script>
```

With:

```
<style>:root{--save-gut:max(env(safe-area-inset-left),0%)}.requestIframe{margin:4.5em 0 0 0;padding:0 var(--save-gut);width:100vw;height:95vh;border:none;position:absolute;top:0}</style>
```

This makes the Jullyseer iFrame take up the whole page, while still being usable on mobile browsers. You can add margin back if needed.
