### ISSUE TITLE
Seasonal Animation Only Visible During Initial Loading Period

### ISSUE THREAD

**Issue by Horridge** [BobHasNoSoul/jellyfin-mods#50]
Attempted to add the Snowstorm animation to my install (with Christmas approaching). However, the animation is only visible briefly during the initial web client loading. Once the home.html has loaded, it disappears. 
![snowstorm](https://github.com/user-attachments/assets/13375f7c-74ab-4184-97bc-687e00079940)

**Comment by BobHasNoSoul** [comment]
What version of jellyfin web are you using? It looks like they have changed
the z index (thus the CSS would need adjusting for the animations) but I
will be updating a few things this weekend (if the wife permits) and I can
put that at the top of the list if you like or you can change the z-index
for the snowstorm manually yourself in the meantime (even use an overide in
customcss block in admin panel) the exact z index will need to be figured
out based on what they changed it to

**Comment by Horridge** [comment]
Jellyfin v10.10.2 installed on Debian 12 (bookworm)

**Comment by chrisbehectik** [comment]
@BobHasNoSoul What code snippet can I add to the custom css block to get this working? Currently running Jellyfin v10.10.3 Docker LSIO.
Not working at all for me through adding into index.html, although, that might be due to my css.

**Comment by BobHasNoSoul** [comment]
@chrisbehectik okay so i have just had a deeper look into this using the latest 10.10.3

i followed the exact same steps as the last versions and it works

to clarify you must do the following.. all of the following.. in the following order

1. download the seasonal folder and place it into the webroot.. so you can access http://192.168.1.XX:8096/web/seasonal/snowflakes.css in your browser.. if you do not have that then you have put that in the wrong folder or have not actually downloaded the seasonal folder.

2. you then need to modify the index.html not any other html inside your webroot add the lines for the correct version you wish to add.

3. you then need to get the file saved then go to your client.. clear the cache or do a forced reload (CTRL+SHIFT+R on some browsers or load it in incognito mode)

4. it will display as expected


for @Horridge it is a css issue with z-index on the snowstorm, i will push an update to this in a few mins i basically now need to move the elements of the server higher up and then layer this inbetween like a sandwich.. great job on the devs part for moving them over again.

**Comment by BobHasNoSoul** [comment]
okay so i will be updating the readme and the files required needed to do this but incase this is faster for you the custom css needed is this add it to your customcss block:

/*fix snowstorm*/
.content-primary, .padded-bottom-page, .page, .pageWithAbsoluteTabs .pageTabContent {  z-index: 4;}
.videoPlayerContainer {  z-index: 3;}
.skinHeader.osdHeader {    z-index: 5 !important;}

you then need to pull the new version of snowstorm.js (this will change the z-index from -1 to 0 (moves it up by one layer) this will be fine for most of the uses but may have some graphical bugs.. if so let me know i havent fully bug tested it yet so.. let me know what you find. and as always you need to reload the cache after or force reload the page.


> Attempted to add the Snowstorm animation to my install (with Christmas approaching). However, the animation is only visible briefly during the initial web client loading. Once the home.html has loaded, it disappears. ![snowstorm](https://private-user-images.githubusercontent.com/26923933/387207009-13375f7c-74ab-4184-97bc-687e00079940.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNTYzMjksIm5iZiI6MTczMjM1NjAyOSwicGF0aCI6Ii8yNjkyMzkzMy8zODcyMDcwMDktMTMzNzVmN2MtNzRhYi00MTg0LTk3YmMtNjg3ZTAwMDc5OTQwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDEwMDAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YTdjY2FiODcxNmQ1NjM0NTRiYjc0NjdhMWUxNGUyMzgyOGY4OTBlZWQ2Y2JiZWQ3Y2NkYzgxMWRmMzcyOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZZ-oKNvZ36-Rh0ZhWyU3hy4vxWeJYMaGX4xV3ADOct4) [ ![snowstorm](https://private-user-images.githubusercontent.com/26923933/387207009-13375f7c-74ab-4184-97bc-687e00079940.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNTYzMjksIm5iZiI6MTczMjM1NjAyOSwicGF0aCI6Ii8yNjkyMzkzMy8zODcyMDcwMDktMTMzNzVmN2MtNzRhYi00MTg0LTk3YmMtNjg3ZTAwMDc5OTQwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDEwMDAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YTdjY2FiODcxNmQ1NjM0NTRiYjc0NjdhMWUxNGUyMzgyOGY4OTBlZWQ2Y2JiZWQ3Y2NkYzgxMWRmMzcyOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZZ-oKNvZ36-Rh0ZhWyU3hy4vxWeJYMaGX4xV3ADOct4) ](https://private-user-images.githubusercontent.com/26923933/387207009-13375f7c-74ab-4184-97bc-687e00079940.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNTYzMjksIm5iZiI6MTczMjM1NjAyOSwicGF0aCI6Ii8yNjkyMzkzMy8zODcyMDcwMDktMTMzNzVmN2MtNzRhYi00MTg0LTk3YmMtNjg3ZTAwMDc5OTQwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDEwMDAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YTdjY2FiODcxNmQ1NjM0NTRiYjc0NjdhMWUxNGUyMzgyOGY4OTBlZWQ2Y2JiZWQ3Y2NkYzgxMWRmMzcyOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZZ-oKNvZ36-Rh0ZhWyU3hy4vxWeJYMaGX4xV3ADOct4) [ ](https://private-user-images.githubusercontent.com/26923933/387207009-13375f7c-74ab-4184-97bc-687e00079940.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNTYzMjksIm5iZiI6MTczMjM1NjAyOSwicGF0aCI6Ii8yNjkyMzkzMy8zODcyMDcwMDktMTMzNzVmN2MtNzRhYi00MTg0LTk3YmMtNjg3ZTAwMDc5OTQwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDEwMDAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YTdjY2FiODcxNmQ1NjM0NTRiYjc0NjdhMWUxNGUyMzgyOGY4OTBlZWQ2Y2JiZWQ3Y2NkYzgxMWRmMzcyOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZZ-oKNvZ36-Rh0ZhWyU3hy4vxWeJYMaGX4xV3ADOct4)

**Comment by chrisbehectik** [comment]
> @chrisbehectik okay so i have just had a deeper look into this using the latest 10.10.3
> 
> i followed the exact same steps as the last versions and it works
> 
> to clarify you must do the following.. all of the following.. in the following order
> 
> 1. download the seasonal folder and place it into the webroot.. so you can access http://192.168.1.XX:8096/web/seasonal/snowflakes.css in your browser.. if you do not have that then you have put that in the wrong folder or have not actually downloaded the seasonal folder.
> 2. you then need to modify the index.html not any other html inside your webroot add the lines for the correct version you wish to add.
> 3. you then need to get the file saved then go to your client.. clear the cache or do a forced reload (CTRL+SHIFT+R on some browsers or load it in incognito mode)
> 4. it will display as expected
> 
> for @Horridge it is a css issue with z-index on the snowstorm, i will push an update to this in a few mins i basically now need to move the elements of the server higher up and then layer this inbetween like a sandwich.. great job on the devs part for moving them over again.

You were right. I was doing something wrong. kept pasting the code a few tags due to the way the file was formatted was hard to tell.

Many thanks!

Don't know if this is a bug or not but the Windows Jellyfin Media Player client shows the animation even during media playing.

**Comment by Horridge** [comment]
> Don't know if this is a bug or not but the Windows Jellyfin Media Player client shows the animation even during media playing.
Ah yes, seeing that on web too 😅

**Comment by Horridge** [comment]
Apologies, you're right, the extra CSS does fix that. I changed the z-index in the JS and thought that was enough!
